%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/noetic/.*$
%global __requires_exclude_from ^/opt/ros/noetic/.*$

Name:           ros-noetic-mesh-navigation
Version:        1.0.1
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS mesh_navigation package

License:        BSD-3
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-noetic-cvp-mesh-planner
Requires:       ros-noetic-dijkstra-mesh-planner
Requires:       ros-noetic-mbf-mesh-core
Requires:       ros-noetic-mbf-mesh-nav
Requires:       ros-noetic-mesh-client
Requires:       ros-noetic-mesh-controller
Requires:       ros-noetic-mesh-layers
Requires:       ros-noetic-mesh-map
BuildRequires:  ros-noetic-catkin
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
The mesh_navigation package provides a layered mesh_map implementation, a Move
Base Flex mesh navigation server, as well as mesh navigation plugins for path
planning and navigation control.

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/noetic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/noetic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    -DCATKIN_BUILD_BINARY_PACKAGE="1" \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%files
/opt/ros/noetic

%changelog
* Wed Oct 27 2021 Sebastian Pütz <spuetz@uos.de> - 1.0.1-1
- Autogenerated by Bloom

* Sat Jan 02 2021 Sebastian Pütz <spuetz@uos.de> - 1.0.0-2
- Autogenerated by Bloom

* Sun Dec 20 2020 Sebastian Pütz <spuetz@uos.de> - 1.0.0-1
- Autogenerated by Bloom

