name: Noetic CI

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ros-tooling/setup-ros@v0.1
        with:
          required-ros-distributions: noetic
      - uses: ros-tooling/action-ros-ci@v0.1
        with:
          package-name: mesh_navigation
          target-ros1-distro: noetic
          vcs-repo-file-url: ""
